// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package cards_service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Card
	Pairing
	Empty
*/
package cards_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Card struct {
	Id    uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Cards []*Card `protobuf:"bytes,3,rep,name=cards" json:"cards,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Card) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Card) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Card) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Pairing struct {
	Parent *Card `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	Child  *Card `protobuf:"bytes,2,opt,name=child" json:"child,omitempty"`
}

func (m *Pairing) Reset()                    { *m = Pairing{} }
func (m *Pairing) String() string            { return proto.CompactTextString(m) }
func (*Pairing) ProtoMessage()               {}
func (*Pairing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pairing) GetParent() *Card {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Pairing) GetChild() *Card {
	if m != nil {
		return m.Child
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Card)(nil), "cards_service.Card")
	proto.RegisterType((*Pairing)(nil), "cards_service.Pairing")
	proto.RegisterType((*Empty)(nil), "cards_service.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CardProvider service

type CardProviderClient interface {
	Create(ctx context.Context, in *Card, opts ...grpc.CallOption) (*Card, error)
	Delete(ctx context.Context, in *Card, opts ...grpc.CallOption) (*Empty, error)
	Embed(ctx context.Context, in *Pairing, opts ...grpc.CallOption) (*Pairing, error)
	Remove(ctx context.Context, in *Pairing, opts ...grpc.CallOption) (*Empty, error)
}

type cardProviderClient struct {
	cc *grpc.ClientConn
}

func NewCardProviderClient(cc *grpc.ClientConn) CardProviderClient {
	return &cardProviderClient{cc}
}

func (c *cardProviderClient) Create(ctx context.Context, in *Card, opts ...grpc.CallOption) (*Card, error) {
	out := new(Card)
	err := grpc.Invoke(ctx, "/cards_service.CardProvider/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardProviderClient) Delete(ctx context.Context, in *Card, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/cards_service.CardProvider/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardProviderClient) Embed(ctx context.Context, in *Pairing, opts ...grpc.CallOption) (*Pairing, error) {
	out := new(Pairing)
	err := grpc.Invoke(ctx, "/cards_service.CardProvider/Embed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardProviderClient) Remove(ctx context.Context, in *Pairing, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/cards_service.CardProvider/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CardProvider service

type CardProviderServer interface {
	Create(context.Context, *Card) (*Card, error)
	Delete(context.Context, *Card) (*Empty, error)
	Embed(context.Context, *Pairing) (*Pairing, error)
	Remove(context.Context, *Pairing) (*Empty, error)
}

func RegisterCardProviderServer(s *grpc.Server, srv CardProviderServer) {
	s.RegisterService(&_CardProvider_serviceDesc, srv)
}

func _CardProvider_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Card)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardProviderServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards_service.CardProvider/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardProviderServer).Create(ctx, req.(*Card))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardProvider_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Card)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardProviderServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards_service.CardProvider/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardProviderServer).Delete(ctx, req.(*Card))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardProvider_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pairing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardProviderServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards_service.CardProvider/Embed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardProviderServer).Embed(ctx, req.(*Pairing))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardProvider_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pairing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardProviderServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards_service.CardProvider/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardProviderServer).Remove(ctx, req.(*Pairing))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cards_service.CardProvider",
	HandlerType: (*CardProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CardProvider_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CardProvider_Delete_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _CardProvider_Embed_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _CardProvider_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x93, 0xb4, 0xd9, 0xe2, 0x68, 0x3d, 0x8c, 0x45, 0x42, 0x4f, 0x61, 0x4f, 0x11, 0x21,
	0x87, 0xaa, 0xa0, 0xe7, 0xea, 0xbd, 0xe4, 0xe2, 0x51, 0xb6, 0xdd, 0x41, 0x07, 0xd2, 0x26, 0x4c,
	0x97, 0x80, 0xff, 0xda, 0x9f, 0x20, 0xd9, 0xe6, 0xd2, 0x92, 0x3d, 0xe6, 0xe5, 0x7d, 0xef, 0xdb,
	0x65, 0x61, 0x7e, 0x24, 0xe9, 0x78, 0x47, 0x65, 0x2b, 0x8d, 0x6b, 0x70, 0xbe, 0x33, 0x62, 0x8f,
	0x5f, 0x43, 0xa8, 0x3f, 0x61, 0xba, 0x36, 0x62, 0xf1, 0x16, 0x12, 0xb6, 0x59, 0x9c, 0xc7, 0xc5,
	0xb4, 0x4a, 0xd8, 0xe2, 0x02, 0x52, 0xc7, 0xae, 0xa6, 0x2c, 0xc9, 0xe3, 0xe2, 0xaa, 0x3a, 0x7d,
	0xe0, 0x03, 0xa4, 0x1e, 0xcf, 0x26, 0xf9, 0xa4, 0xb8, 0x5e, 0xdd, 0x95, 0x67, 0x63, 0x65, 0xbf,
	0x54, 0x9d, 0x1a, 0xda, 0xc0, 0x6c, 0x63, 0x58, 0xf8, 0xf0, 0x8d, 0x8f, 0xa0, 0x5a, 0x23, 0x74,
	0x70, 0x7e, 0x3f, 0x80, 0x0d, 0x15, 0xaf, 0xf8, 0xe1, 0xda, 0x7a, 0x71, 0x50, 0xd1, 0x37, 0xf4,
	0x0c, 0xd2, 0x8f, 0x7d, 0xeb, 0x7e, 0x57, 0x7f, 0x31, 0xdc, 0xf4, 0x3f, 0x36, 0xd2, 0x74, 0x6c,
	0x49, 0xf0, 0x19, 0xd4, 0x5a, 0xc8, 0x38, 0xc2, 0x31, 0x7e, 0x39, 0x16, 0xea, 0x08, 0x5f, 0x40,
	0xbd, 0x53, 0x4d, 0x21, 0x6a, 0x71, 0x11, 0x7a, 0xb7, 0x8e, 0xf0, 0xad, 0x3f, 0xc6, 0x96, 0x2c,
	0xde, 0x5f, 0x14, 0x86, 0xfb, 0x2f, 0x03, 0xb9, 0x8e, 0xf0, 0x15, 0x54, 0x45, 0xfb, 0xa6, 0xa3,
	0x20, 0x1b, 0x90, 0x6e, 0x95, 0x7f, 0xcd, 0xa7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xc9,
	0x21, 0x8f, 0xde, 0x01, 0x00, 0x00,
}
